//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entitiy_Proje_Urun_Uygulama
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ADMIN
    {
        public byte K_ID { get; set; }
        public string K_ADI { get; set; }
        public string K_SIFRE { get; set; }
    }
}
